# Generated by Django 2.2.12 on 2020-11-22 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0002_auto_20201122_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='languages',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='languages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyProfile.Language'),
            preserve_default=False,
        ),
    ]
