# Generated by Django 2.2.12 on 2020-11-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0003_auto_20201122_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='Level',
        ),
    ]
