# Generated by Django 2.2.12 on 2020-11-22 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0004_remove_language_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='level',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='skills',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyProfile.Skills'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(choices=[('ML', 'Machine Learning'), ('DL', 'Deep Learning'), ('CV', 'Computer Vision'), ('NLP', 'Natural Language Processing'), ('PR', 'Programming')], max_length=100),
        ),
    ]
