# Generated by Django 2.2.12 on 2020-11-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0005_auto_20201122_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skill',
        ),
        migrations.AddField(
            model_name='skills',
            name='description',
            field=models.CharField(default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='MyProfile.Skills'),
        ),
    ]
