# Generated by Django 2.2.12 on 2020-11-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0006_auto_20201122_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='MyProfile.Skills'),
        ),
    ]
