# Generated by Django 2.2.12 on 2020-11-22 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0008_auto_20201122_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='skills',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyProfile.Skills'),
            preserve_default=False,
        ),
    ]
