# Generated by Django 2.2.12 on 2020-11-22 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0009_auto_20201122_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProfile.Skills'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='social_media',
            field=models.ManyToManyField(blank=True, to='MyProfile.socialMedia'),
        ),
    ]
