# Generated by Django 2.2.12 on 2020-11-22 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0010_auto_20201122_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyProfile.Skills'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(choices=[('link', 'linkdin'), ('link', 'twitter'), ('link', 'github')], max_length=100),
        ),
    ]
