# Generated by Django 2.2.12 on 2020-11-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyProfile', '0012_auto_20201123_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='myprofile',
            old_name='languages',
            new_name='language',
        ),
        migrations.RemoveField(
            model_name='language',
            name='language',
        ),
        migrations.RemoveField(
            model_name='language',
            name='level',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='skills',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyProfile.Skill'),
            preserve_default=False,
        ),
    ]
