# Generated by Django 2.2.12 on 2020-10-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Porjects',
        ),
    ]
