# Generated by Django 2.2.12 on 2020-10-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('technology', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
    ]
